# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-03 11:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tit', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Days',
            new_name='Day',
        ),
        migrations.RenameModel(
            old_name='Students',
            new_name='Student',
        ),
    ]
