# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-03 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tit', '0002_auto_20160503_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='days_attended',
        ),
        migrations.AddField(
            model_name='student',
            name='days_attended',
            field=models.IntegerField(default=0),
        ),
    ]
